### ISSUE TITLE
ERROR: VUID-vkCmdBuildAccelerationStructuresKHR-geometry-03673 

### ISSUE THREAD

**Issue by kyamant** [Apress/Ray-Tracing-Gems-II#5]
ERROR: VUID-vkCmdBuildAccelerationStructuresKHR-geometry-03673 
 --> Validation Error: [ VUID-vkCmdBuildAccelerationStructuresKHR-geometry-03673 ] Object 0: handle = 0x19a7cf724f0, type = VK_OBJECT_TYPE_DEVICE; Object 1: handle = 0xd5b26f0000000010, type = VK_OBJECT_TYPE_BUFFER; | MessageID = 0x8a7de95d | vkCmdBuildAccelerationStructuresKHR(): The buffer associated with pInfos[0].pGeometries[0].geometry.instances.data was not created with VK_BUFFER_USAGE_ACCELERATION_STRUCTURE_BUILD_INPUT_READ_ONLY_BIT_KHR. The Vulkan spec states: The buffers from which the buffer device addresses for all of the geometry.triangles.vertexData, geometry.triangles.indexData, geometry.triangles.transformData, geometry.aabbs.data, and geometry.instances.data members of all pInfos[i].pGeometries and pInfos[i].ppGeometries are queried must have been created with the VK_BUFFER_USAGE_ACCELERATION_STRUCTURE_BUILD_INPUT_READ_ONLY_BIT_KHR usage flag (https://vulkan.lunarg.com/doc/view/1.3.216.0/windows/1.3-extensions/vkspec.html

**Comment by acmarrs-nvidia** [comment]
Hi @kyamant - thanks for your message! I've forwarded this to the authors of Chapter 16. They'll either respond here directly or I'll post for them after they've had a chance to review.

**Comment by mattruschnv** [comment]
Hi @kyamant. Can you please provide us with a bit more information please? Were you running out of the sample repo, your own code, etc? Can you provide us a repo case either in github or otherwise? Thanks!

**Comment by kyamant** [comment]
I followed the  provided instructions to clone the repo, build and run the sample.
Using Vulkan SDK 1.3.216.0, RTX 3070 ti 516.59 on windows 10

**Comment by acmarrs-nvidia** [comment]
Thanks @kyamant. The sample code has been updated with a fix that matches the PR from @techlabxe.
