### ISSUE TITLE
Chapater 3, Listing 3-6, Generalized Panini projection

### ISSUE THREAD

**Issue by caxieyou** [Apress/Ray-Tracing-Gems-II#6]
in the shader sample code, where is the resolution.x and y came from?  in Line 4
what's the difference between the resolution and imageSize? 

and where is the hvPan came from? in Line 13 and 14

what does d mean in Line 16

this whole code is so confusing.... -_-!!!

**Comment by acmarrs-nvidia** [comment]
Hi there @caxieyou. I believe the answers to your questions are [in the errata here.](https://github.com/Apress/Ray-Tracing-Gems-II/blob/main/errata.md)
